# Generated by Django 2.2 on 2021-08-10 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='active',
        ),
    ]
